### Obtener todos los usuarios  
GET https://tourtales.3.us-1.fl0.io/api/usuarioTurista

### Recuperar un usuario Turista por correo
GET http://localhost:1234/api/usuarioTurista/ar.contreras372@gmail.com

### Crear un nuevo usuario
POST http://localhost:1234/api/authenticator/registro/usuarioTurista
Content-Type: application/json

{ 
    "Nombre": "Angel",
    "Apellido": "Contreras",
    "Correo": "cgrazo7.cgr@gmail.com",
    "Contrasena": "12345",
    "Fecha_Nacimiento": "2003-01-05"
}

### Crear un nuevo usuario 2
POST http://localhost:1234/api/authenticator/registro/usuarioTurista
Content-Type: application/json

{ 
    "Nombre": "Arcy",
    "Apellido": "Contreras",
    "Correo": "ar.contreras372@gmail.com",
    "Contrasena": "12345",
    "Fecha_Nacimiento": "2003-01-05"
}

### Cambiar contraseña
POST http://localhost:1234/api/usuarioTurista/cambiarContrasena
Content-Type: application/json

{ 
    "id_Turista": 1,
    "Contrasena": "arcy"
}